### ISSUE TITLE
Show attached tags in experiment detail screen

### ISSUE THREAD

**Issue by SGevorg** [aimhubio/aimde#20]
**Problem**
Experiments can be tagged after they are created. Tags are visible in the panel but not visible on the `Experiments` page (the commits).

**Solution**
Add visual indicatin on the experiment page that shows which experiments have been tagged.

**Comment by jialin-wu-02** [comment]
Related PR: #31

**Comment by SGevorg** [comment]
BTW @jialin-wu-02 you can attach the issue to the #31 PR and it will also close the issue automatically once the PR is merged.
