### ISSUE TITLE
Is there any way to change the method of interpolation?

### ISSUE THREAD

**Issue by hunan-rostomyan** [aimhubio/aimde#83]
I have a continuous variable "f-score" that I'm tracking at discrete intervals, one per epoch. I see this nice plot being generated for it:
<img width="1131" alt="Screen Shot 2020-09-15 at 5 25 39 PM" src="https://user-images.githubusercontent.com/5122980/93278148-b26f5b80-f778-11ea-99fe-ae34fa92b3eb.png">

I'd like to just see straight lines instead of curves connecting the points, roughly, something like this:

<img width="1131" alt="Screen Shot 2020-09-15 at 5 25 39 PM" src="https://user-images.githubusercontent.com/5122980/93278394-6244c900-f779-11ea-9046-9b5999576a2a.png">

Is this possible?

**Comment by gorarakelyan** [comment]
Hi @hunan-rostomyan,

Thanks for feedback. The ability of selecting which interpolation method(linear or cubic) to apply will be available in the next release.
